version: "3.6"

services:

  web:
    image: nginx:alpine
    container_name: mittings-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - api
      - adminer
    networks:
      - mittings-network

  api:
    image: mittings-api:1.0
    container_name: mittings-api
    networks:
      - mittings-network
    depends_on:
      - db

  db:
    build: docker/postgres
    container_name: mittings-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    volumes:
      - mittings-db-config-data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    networks:
      - mittings-network

  adminer:
    image: adminer
    container_name: mittings-adminer
    restart: always
    depends_on:
      - db
    networks:
      - mittings-network

#  frontend:
#    build: docker/frontend
#    container_name: mittings-frontend
#    command: bash -c "npm run dev"
#    user: 1000:1000
#    volumes:
#      - ./frontend:/app
#    networks:
#      - mittings-network

networks:
  mittings-network:

volumes:
  mittings-db-config-data:
