version: "3.6"

services:
  web:
    image: nginx:alpine
    container_name: meetings-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/dev/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - api
      - adminer
    networks:
      - meetings-network

  api:
    build: docker/backend
    container_name: meetings-api
    command: gradle bootRun
    ports:
      - 5005:5005
    volumes:
      - .:/app
    networks:
      - meetings-network
    depends_on:
      - db

  db:
    build: docker/postgres
    container_name: meetings-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    volumes:
      - meetings-db-config-data:/var/lib/postgresql/data
      - ./logs/dev/postgres:/var/log/postgresql
    networks:
      - meetings-network

  adminer:
    image: adminer
    container_name: meetings-adminer
    restart: always
    depends_on:
      - db
    networks:
      - meetings-network

  frontend:
    build: docker/frontend
    container_name: meetings-frontend
    tty: true
    user: 1000:1000
    volumes:
      - ./frontend:/app
    networks:
      - meetings-network

networks:
  meetings-network:

volumes:
  meetings-db-config-data: