spring:
  main:
    allow-bean-definition-overriding: true

  # ===============================
  # DATABASE CONNECTION
  # ===============================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/dev
    username: dev
    password: dev

  # ===============================
  # JPA / HIBERNATE
  # ===============================

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false

  # ===============================
  # SECURITY
  # ===============================
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
